# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine mypy build
        pip install "conan==1.59.0" --use-pep517
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        stubgen -p conans --include-private
        stubgen -p conan --include-private
        mkdir ./gen
        mkdir ./gen/conan-stubs
        mkdir ./gen/conans-stubs
        cp -r ./out/conan/* ./gen/conan-stubs
        cp -r ./out/conans/* ./gen/conans-stubs
        cp -rf ./src/conans-stubs/* ./gen/conans-stubs
        python3 -m build
        python3 -m twine upload dist/*

